# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/hadite/issues"

[[mods]]
modId="haditecoal"
version="${version}"
displayName="akkamaddi's Hadite Coal"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/hadite/1.15/update.json"
displayURL="http://minecraft.curseforge.com/projects/akkamaddis-hadite-coal"
credits="Thanks to akkamaddi for creating the original mod and to Sinhika for porting and maintaining it."
authors="akkamaddi, Sinhika"
description='''Hadite Coal, a utility ore from the Nether, plus two alloys.
'''

[[dependencies.haditecoal]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.haditecoal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.haditecoal]]
    modId="simpleores"
    mandatory=true
    versionRange="[1.14.4-2.0.9.0,]"
    ordering="NONE"
    side="BOTH"    

[[dependencies.haditecoal]]
    modId="fusion"
    mandatory=true
    versionRange="[1.14.4-2.5.4.0,]"
    ordering="NONE"
    side="BOTH"    
